# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/moe-leaeval-layer2-prework',
                'doc_host': 'https://nick-dsaid.github.io',
                'git_url': 'https://github.com/nick-dsaid/moe-leaeval-layer2-prework',
                'lib_path': 'moe_leaeval_layer2_prework'},
  'syms': { 'moe_leaeval_layer2_prework.core': { 'moe_leaeval_layer2_prework.core.foo': ( 'core.html#foo',
                                                                                          'moe_leaeval_layer2_prework/core.py')}}}
